# Generated by Django 4.1.7 on 2023-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('convidado_pode_pausar', models.BooleanField(default=False)),
                ('pedido_para_pular', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
